name: Firmware build

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build ESP-IDF firmware
        uses: espressif/esp-idf-ci-action@v1
        with:
          target: esp32
          path: firmware/esp_idf_ams_han_gateway_wroom32d
          command: idf.py build
